# fuzzel config - Catppuccin Macchiato

font=IosevkaTerm Nerd Font:size=14
dpi-aware=auto
icon-theme=Tela-circle-purple-dark
icons-enabled=yes
show-actions=yes
fields=filename,name,generic
match-mode=fzf
lines=10
width=35
horizontal-pad=20
vertical-pad=8
inner-pad=6
image-size-ratio=0.5
anchor=center
layer=overlay
exit-on-keyboard-focus-loss=yes
prompt=  

[colors]
background=24273aee
text=cad3f5ff
prompt=c6a0f6ff
placeholder=6e738dff
input=cad3f5ff
match=c6a0f6ff
selection=363a4fff
selection-text=cad3f5ff
selection-match=f5a97fff
border=c6a0f6ff

[border]
width=1
radius=8
