bind_to_address     "127.0.0.1"
#bind_to_address    "~/.config/mpd/socket"
music_directory     "~/Music"
playlist_directory  "~/.mpd/playlists"
db_file             "~/.mpd/mpd.db"
log_file            "~/.mpd/mpd.log"
pid_file            "~/.mpd/mpd.pid"
state_file          "~/.mpd/mpdstate"

# PipeWire (via pipewire-pulse compatibility layer)
audio_output {
    type            "pipewire"
    name            "PipeWire Output"
}

# FIFO output for ncmpcpp visualizer
audio_output {
    type            "fifo"
    name            "Visualizer feed"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}
