# Alacritty Configuration (TOML)

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
]
live_config_reload = true

[window]
padding = { x = 8, y = 2 }
decorations = "None"
dynamic_padding = true
opacity = 0.95

[font]
size = 16.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Home"
chars = "\u001b[H"

[[keyboard.bindings]]
key = "End"
chars = "\u001b[F"

[[keyboard.bindings]]
key = "Insert"
chars = "\u001b[2~"

[[keyboard.bindings]]
key = "Delete"
chars = "\u001b[3~"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
