import = ["~/.config/alacritty/catppuccin-mocha.toml"]
shell = "/usr/bin/zsh"

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "F", mods = "Control", action = "ToggleMaximized" }
]

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true 
decorations = "None"
opacity = 0.9

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Light" }
bold = { family = "Hack Nerd Font Mono", style = "Medium" }
italic = { family = "Hack Nerd Font Mono", style = "Light Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size = 11.25
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
